---
title: "Ag Yield Prediction - baseline"
author: "Beau Smit"
date: "2/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(forecast)
```

```{r}
ag_df = read.csv('MN_Ag_YieldsAndInputs.csv')
```

```{r}
# only keep years where all 3 commodities have values
ag_df = ag_df[!is.na(ag_df$Soy_BUperAcre),] %>% arrange(Year)

# make into time series
corn_ts <- ts(ag_df$Corn_BUperAcre, start = min(ag_df$Year), frequency = 1)
wheat_ts <- ts(ag_df$Wheat_BUperAcre, start = min(ag_df$Year), frequency = 1)
soy_ts <- ts(ag_df$Soy_BUperAcre, start = min(ag_df$Year), frequency = 1)

# split train and test sets
first_test_yr <- 2017

corn_train <- window(corn_ts, end=first_test_yr-1)
corn_test <- window(corn_ts, start=first_test_yr)

wheat_train <- window(wheat_ts, end=first_test_yr-1)
wheat_test <- window(wheat_ts, start=first_test_yr)

soy_train <- window(soy_ts, end=first_test_yr-1)
soy_test <- window(soy_ts, start=first_test_yr)
```

```{r}
h <- 5

# naive method
plot(naive(corn_train, h=h))
plot(naive(wheat_train, h=h))
plot(naive(soy_train, h=h))

# actual estimates
naive_predictions <- naive(corn_train, h=h)$mean
```

```{r}
plot(rwf(corn_train, h=h, drift=T))
plot(rwf(wheat_train, h=h, drift=T))
plot(rwf(soy_train, h=h, drift=T))

# actual estimates
drift_predictions <- rwf(corn_train, h=h, drift=T)$mean
```

```{r}
# holt method
plot(holt(corn_train, h=h, damped=T))
plot(holt(wheat_train, h=h, damped=T, exponential=T))
plot(holt(soy_train, h=h, damped=T))

# actual estimates
holt_predictions <- holt(corn_train, h=h, damped=T)$mean
```

```{r}
lam <- BoxCox.lambda(corn_train)
# auto ARIMA, auto BoxCox
arima_mdl <- auto.arima(corn_train, lambda = lam)
arima_predictions <- (forecast(arima_mdl, h=h))$mean
plot(forecast(arima_mdl, h=h))
```
