---
title: "Model Stacking"
author: "Beau Smit"
date: "2/28/2022"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(caret)
library(randomForest)
library(e1071)
```

```{r}
baseline_preds <- read.csv("../data/baseline_predictions.csv")

corn_baseline_preds <- baseline_preds %>% filter(crop == "corn")
wheat_baseline_preds <- baseline_preds %>% filter(crop == "wheat")
soy_baseline_preds <- baseline_preds %>% filter(crop == "soy")
```

### Build stacking model

```{r}
train_test_split <- function(predictions, test_yr){
  # 20 year sliding window to train stacked model
  train <- predictions %>% filter((year < test_yr) & (year >= (test_yr - 20)))
  test <- predictions %>% filter(year == test_yr)
  
  train_test <- list("train" = train, "test" = test)
  return(train_test)
}
```

```{r}
predict_stacked_mdl <- function(predictions){
  set.seed(6307)
  
  stacked_mdl_preds <- c()
  
  for (test_yr in 2016:2020){
    
    # split into training and testing sets for X and y
    train_test <- train_test_split(predictions, test_yr)
    train <- train_test$train %>% select(naive_t.1, holt_t.1, arima_t.1, true_value_t.1)
    test <- train_test$test %>% select(naive_t.1, holt_t.1, arima_t.1, true_value_t.1)
    
    # train stacking model
    #stacking_mdl <- glm(true_value_t.1 ~ naive_t.1 + holt_t.1 + arima_t.1, data=train)
    # linear model did not perform very well
    stacking_mdl <- randomForest(true_value_t.1 ~ ., data=train, ntree=1000, nodesize=18)
    #stacking_mdl <- svm(true_value_t.1 ~ ., data = train, kernel = "linear", cost = 1)
    
    # predict on following year
    new_row <- c(test_yr, predict(stacking_mdl, test), test$true_value_t.1)
    stacked_mdl_preds <- rbind(stacked_mdl_preds, new_row)
  
  }
  colnames(stacked_mdl_preds) <- c("year", "forecast", "actual")
  return(stacked_mdl_preds %>% as.data.frame())
}
```

```{r}
# stacked model predictions for 2017-2021
corn_stacked_preds <- predict_stacked_mdl(corn_baseline_preds)
wheat_stacked_preds <- predict_stacked_mdl(wheat_baseline_preds)
soy_stacked_preds <- predict_stacked_mdl(soy_baseline_preds)
```

```{r}
get_MAPE <- function(true_values, predictions){
  ape <- ((abs(true_values - predictions)) / abs(true_values)) * 100
  mape <- round(mean(ape), digits = 2)
  return(mape)
}
```

### Compare Models using MAPE

```{r}
print("stacked model")
get_MAPE(corn_stacked_preds$actual, corn_stacked_preds$forecast)
get_MAPE(wheat_stacked_preds$actual, wheat_stacked_preds$forecast)
get_MAPE(soy_stacked_preds$actual, soy_stacked_preds$forecast)
```

```{r}
corn_baseline_preds_subset <- corn_baseline_preds %>% filter(year >= 2016)
wheat_baseline_preds_subset <- wheat_baseline_preds %>% filter(year >= 2016)
soy_baseline_preds_subset <- soy_baseline_preds %>% filter(year >= 2016)
```


```{r}
print("naive model")
get_MAPE(corn_baseline_preds_subset$naive_t.1, corn_baseline_preds_subset$true_value_t.1)
get_MAPE(wheat_baseline_preds_subset$naive_t.1, wheat_baseline_preds_subset$true_value_t.1)
get_MAPE(soy_baseline_preds_subset$naive_t.1, soy_baseline_preds_subset$true_value_t.1)
```

```{r}
print("Holt model")
get_MAPE(corn_baseline_preds_subset$holt_t.1, corn_baseline_preds_subset$true_value_t.1)
get_MAPE(wheat_baseline_preds_subset$holt_t.1, wheat_baseline_preds_subset$true_value_t.1)
get_MAPE(soy_baseline_preds_subset$holt_t.1, soy_baseline_preds_subset$true_value_t.1)
```

```{r}
print("ARIMA model")
get_MAPE(corn_baseline_preds_subset$arima_t.1, corn_baseline_preds_subset$true_value_t.1)
get_MAPE(wheat_baseline_preds_subset$arima_t.1, wheat_baseline_preds_subset$true_value_t.1)
get_MAPE(soy_baseline_preds_subset$arima_t.1, soy_baseline_preds_subset$true_value_t.1)
```

```{r}
VAR_predictions <- read.csv("../data/VAR_predictions.csv")

VAR_corn_preds <- VAR_predictions %>% 
  filter(crop == "corn") %>%
  right_join(., corn_baseline_preds %>% select(year, starts_with("true_value")), by="year")
VAR_wheat_preds <- VAR_predictions %>% 
  filter(crop == "wheat") %>%
  right_join(., wheat_baseline_preds %>% select(year, starts_with("true_value")), by="year")
VAR_soy_preds <- VAR_predictions %>% 
  filter(crop == "soy") %>%
  right_join(., soy_baseline_preds %>% select(year, starts_with("true_value")), by="year")
```

```{r}
print("VARcw model")
get_MAPE(VAR_corn_preds$VARcw_t.1, VAR_corn_preds$true_value_t.1)
get_MAPE(VAR_wheat_preds$VARcw_t.1, VAR_wheat_preds$true_value_t.1)
get_MAPE(VAR_soy_preds$VARcw_t.1, VAR_soy_preds$true_value_t.1)
```

```{r}
print("VAR3 model")
get_MAPE(VAR_corn_preds$VAR3_t.1, VAR_corn_preds$true_value_t.1)
get_MAPE(VAR_wheat_preds$VAR3_t.1, VAR_wheat_preds$true_value_t.1)
get_MAPE(VAR_soy_preds$VAR3_t.1, VAR_soy_preds$true_value_t.1)
```

## Plot forecasts

```{r}
plot_predictions <- function(regular_preds, stacked_preds, commodity){
  
  baseline_plot_df <- regular_preds %>% filter(year >= 2016)
  
  ggplot() + 
    geom_line(data=regular_preds, aes(x=year+1, y=true_value_t.1)) + 
    geom_line(data=stacked_preds, aes(x=year+1, y=forecast, color='stacked baseline')) + 
    geom_line(data=baseline_plot_df, aes(x=year+1, y=naive_t.1, color='naive')) + 
    geom_line(data=baseline_plot_df, aes(x=year+1, y=holt_t.1, color='Holt')) + 
    geom_line(data=baseline_plot_df, aes(x=year+1, y=arima_t.1, color='ARIMA')) + 
    ggtitle(commodity) + 
    xlab("Year") + 
    ylab("Bushels per acre")
  
}
```

```{r}
plot_predictions(corn_baseline_preds, corn_stacked_preds, "corn") + 
  geom_line(data=VAR_corn_preds %>% filter(year >= 2016), aes(x=year+1, y=VARcw_t.1, col="VAR"))

plot_predictions(wheat_baseline_preds, wheat_stacked_preds, "wheat") + 
  geom_line(data=VAR_wheat_preds %>% filter(year >= 2016), aes(x=year+1, y=VARcw_t.1, col="VAR"))

plot_predictions(soy_baseline_preds, soy_stacked_preds, "soy")
```

```{r}
current_year <- 2020
a <- corn_baseline_preds %>% filter(year == current_year) %>% select(starts_with(("naive"))) %>% t() %>% as.data.frame() %>% mutate(year = seq(current_year, current_year+4, 1))
b <- corn_baseline_preds %>% filter(year == current_year) %>% select(starts_with(("true"))) %>% t() %>% as.data.frame() %>% mutate(year = seq(current_year, current_year+4, 1))
c <- VAR_corn_preds %>% filter(year == current_year) %>% select(starts_with(("VARcw"))) %>% t() %>% as.data.frame() %>% mutate(year = seq(current_year, current_year+4, 1))

ggplot() + 
  geom_line(data = corn_baseline_preds %>% filter(year < current_year), aes(x=year+1, y=true_value_t.1)) + 
  geom_line(data = a, aes(x=year+1, y=V1, col="naive")) + 
  geom_line(data = b, aes(x=year+1, y=V1, col="observed")) + 
  geom_line(data = c, aes(x=year+1, y=V1, col="VAR"))
```

