---
title: "andresc_dataexploration"
author: "Andres Crucetta"
date: "2/25/2022"
output: html_document
---
```{r}
install.packages('randomForest', repos = "http://cran.us.r-project.org")
install.packages('caret', repos = "http://cran.us.r-project.org")
```

```{r}
library(httr)
library(usdarnass)
library(tidyverse)
library(forecast)
library(knitr)
library("tidyverse")
library("forecast")
library("TSA")
library("tseries")
library("MuMIn")
library("randomForest")
library(gbm)
library(caret)
```

```{r}
setwd("~/Documents/GitHub/Time-Series")
library(readr)
ag_df <- read_csv("data/MN_Ag_YieldsAndInputs.csv")
agro_features <- read_csv("data/CMIP5_Agro_year.csv",col_names = FALSE)
```



```{r reading_csv}
# only keep years where all 3 commodities have values
ag_df = ag_df[!is.na(ag_df$Soy_BUperAcre),] %>% arrange(Year)

# make into time series
corn_ts <- ts(ag_df$Corn_BUperAcre, start = min(ag_df$Year), frequency = 1)
wheat_ts <- ts(ag_df$Wheat_BUperAcre, start = min(ag_df$Year), frequency = 1)
soy_ts <- ts(ag_df$Soy_BUperAcre, start = min(ag_df$Year), frequency = 1)

# split train and test sets
first_test_yr <- 2017

corn_train <- window(corn_ts, end=first_test_yr-1)
corn_test <- window(corn_ts, start=first_test_yr)

wheat_train <- window(wheat_ts, end=first_test_yr-1)
wheat_test <- window(wheat_ts, start=first_test_yr)

soy_train <- window(soy_ts, end=first_test_yr-1)
soy_test <- window(soy_ts, start=first_test_yr)
```

```{r}
autoplot(corn_ts,main="Corn Production 1934-2016")
autoplot(diff(corn_ts),main="Differenced Corn Production 1934-2016")

autoplot(wheat_ts,main="Wheat Production 1934-2016")
autoplot(diff(wheat_ts),main="Differenced Wheat Production 1934-2016")

autoplot(soy_ts,main="Soy Production 1934-2016")
autoplot(diff(soy_ts),main="Differenced Soy Production 1934-2016")

```



```{r}
lag_order <- 6 # the desired number of lags (6 years)
horizon <- 5 # the forecast horizon (5 years)

corn_embed <- embed(corn_ts, lag_order+1)
soy_embed <- embed(soy_ts, lag_order+1)
wheat_embed <- embed(wheat_ts, lag_order+1)

y_train_corn <- head(corn_embed[, 1],77) # the target
X_train_corn <- head(corn_embed[, -1],77) # everything but the target

y_train_wheat <- head(wheat_embed[, 1],77) # the target
X_train_wheat <- head(wheat_embed[, -1],77) # everything but the target

y_train_soy <- head(soy_embed[, 1],77) # the target
X_train_soy <- head(soy_embed[, -1],77) # everything but the target

y_test_corn <- window(corn_ts, start = c(2016), end = c(2020))
X_test_corn <- tail(corn_embed[,-1],5)

y_test_soy <- window(soy_ts, start = c(2016), end = c(2020))
X_test_soy <- tail(soy_embed[,-1],5)

y_test_wheat <- window(wheat_ts, start = c(2016), end = c(2020))
X_test_wheat <- tail(wheat_embed[,-1],5)
```

```{r ts_crossval}
#### creating sampling seeds ####
set.seed(123)
seeds <- vector(mode = "list", length = 528)
for(i in 1:527) seeds[[i]] <- sample.int(1000, 5)

## For the last model:
seeds[[528]] <- sample.int(1000, 1)

#########
myTimeControl <- trainControl(method = "timeslice",
                              initialWindow = 60,
                              horizon = 5,
                              fixedWindow = TRUE,
                              allowParallel = TRUE,
                              seeds = seeds)

colnames(X_train_corn) <- c('Lag1','Lag2','Lag3','Lag4','Lag5','Lag6')
colnames(X_test_corn) <- c('Lag1','Lag2','Lag3','Lag4','Lag5','Lag6')
colnames(X_train_soy) <- c('Lag1','Lag2','Lag3','Lag4','Lag5','Lag6')
colnames(X_test_soy) <- c('Lag1','Lag2','Lag3','Lag4','Lag5','Lag6')
colnames(X_train_wheat) <- c('Lag1','Lag2','Lag3','Lag4','Lag5','Lag6')
colnames(X_test_wheat) <- c('Lag1','Lag2','Lag3','Lag4','Lag5','Lag6')

tuneLength.num <- 5

rf.mod.corn <- train(x=X_train_corn,
                y=y_train_corn,
                method = "rf",
                ntree=5,
                trControl = myTimeControl,
                tuneLength=tuneLength.num,
                metric='MAE')

gbm.mod.corn <- train(x=X_train_corn,
                y=y_train_corn,
                method = "gbm",
                trControl = myTimeControl,
                tuneLength=tuneLength.num,
                metric='MAE')

rf.mod.soy <- train(x=X_train_soy,
                y=y_train_soy,
                method = "rf",
                ntree=5,
                trControl = myTimeControl,
                tuneLength=tuneLength.num,
                metric='MAE')

gbm.mod.soy <- train(x=X_train_soy,
                y=y_train_soy,
                method = "gbm",
                trControl = myTimeControl,
                tuneLength=tuneLength.num,
                metric='MAE')

rf.mod.wheat <- train(x=X_train_wheat,
                y=y_train_wheat,
                method = "rf",
                ntree=5,
                trControl = myTimeControl,
                tuneLength=tuneLength.num,
                metric='MAE')

gbm.mod.wheat <- train(x=X_train_wheat,
                y=y_train_wheat,
                method = "gbm",
                trControl = myTimeControl,
                tuneLength=tuneLength.num,
                metric='MAE')
```

```{r testing}
forecasts_rf_corn <- predict(rf.mod.corn, X_test_corn)
forecasts_gbm_corn <- predict(gbm.mod.corn, X_test_corn)

forecasts_rf_soy <- predict(rf.mod.soy, X_test_soy)
forecasts_gbm_soy <- predict(gbm.mod.soy, X_test_soy)

forecasts_rf_wheat <- predict(rf.mod.wheat, X_test_wheat)
forecasts_gbm_wheat <- predict(gbm.mod.wheat, X_test_wheat)

```

```{r}
# convert to ts format
y_pred_rf_corn <- ts(
  forecasts_rf_corn,
  start = c(2016),
  frequency = 1
)

y_pred_gbm_corn <- ts(
  forecasts_gbm_corn,
  start = c(2016),
  frequency = 1
)

# convert to ts format
y_pred_rf_soy <- ts(
  forecasts_rf_soy,
  start = c(2016),
  frequency = 1
)

y_pred_gbm_soy <- ts(
  forecasts_gbm_soy,
  start = c(2016),
  frequency = 1
)
# convert to ts format
y_pred_rf_wheat <- ts(
  forecasts_rf_wheat,
  start = c(2016),
  frequency = 1
)

y_pred_gbm_wheat <- ts(
  forecasts_gbm_wheat,
  start = c(2016),
  frequency = 1
)

benchmark_corn <- forecast(naive(corn_train), h = horizon)
benchmark_soy <- forecast(naive(soy_train), h = horizon)
benchmark_wheat <- forecast(naive(wheat_train), h = horizon)

autoplot(corn_train) +
  autolayer(y_pred_rf_corn,series="Random Forest Prediction")+
  autolayer(y_test_corn,series="Actual Values") +
  autolayer(benchmark_corn$mean,series="Naive Forecast")+
  autolayer(y_pred_gbm_corn,series="Gradient Boost")

autoplot(soy_train) +
  autolayer(y_pred_rf_soy,series="Random Forest Prediction")+
  autolayer(y_test_soy,series="Actual Values") +
  autolayer(benchmark_soy$mean,series="Naive Forecast")+
  autolayer(y_pred_gbm_soy,series="Gradient Boost")

autoplot(wheat_train) +
  autolayer(y_pred_rf_wheat,series="Random Forest Prediction")+
  autolayer(y_test_wheat,series="Actual Values") +
  autolayer(benchmark_wheat$mean,series="Naive Forecast")+
  autolayer(y_pred_gbm_wheat,series="Gradient Boost")
```


```{r}
accuracy(y_pred_rf_corn, y_test_corn)
accuracy(y_pred_gbm_corn, y_test_corn)

accuracy(y_pred_rf_wheat, y_test_wheat)
accuracy(y_pred_gbm_wheat, y_test_wheat)

accuracy(y_pred_rf_soy, y_test_soy)
accuracy(y_pred_gbm_soy, y_test_soy)
```

```{r}
rf.mod.corn[['results']]
```


### Alternative CV

```{r predictive_function}

rf_predictions <- function(train,test){
  
  rf_model <- randomForest(x=train[,-1],y=train[,1])
  rf_preds <- (predict(rf_model,test[,-1]))
  preds_row <- c(rf_preds)
  return(preds_row)
}

gbm_predictions <- function(train,test){
  
  gbm_model <- gbm(T ~ ., data = train,distribution = "gaussian",n.trees = 10000,
                  shrinkage = 0.01, interaction.depth = 4)
  gbm_preds <- (predict(gbm_model,test[,-1]))
  preds_row <- c(gbm_preds)
  return(preds_row)
}
```


```{r ts_cv}

corn_preds <- c()
wheat_preds <- c()
soy_preds <- c()

lag_order <- 6 # the desired number of lags (6 years)
horizon <- 5 # the forecast horizon (5 years)

for (first_test_yr in 1998:2016){
  
  # Corn Embedded
  corn_embed_tst <- embed(corn_ts,5)
  corn_train <- window(ts(corn_embed_tst,start=1938), start=first_test_yr-60, end=first_test_yr)
  corn_test <- window(ts(corn_embed_tst,start=1938), start=first_test_yr+1,end=first_test_yr+5)
  colnames(corn_train) <- c("T","T-1","T-2","T-3","T-4")
  colnames(corn_test) <- c("T","T-1","T-2","T-3","T-4")
  
  # get all baseline model predictions and add in first test year and true value
  corn_row <- c(first_test_yr, "corn", rf_predictions(corn_train, corn_test), gbm_predictions(corn_train,corn_test),corn_test[0:5])
  corn_preds <- rbind(corn_preds, corn_row)
  
  wheat_embed_tst <- embed(wheat_ts,5)
  wheat_train <- window(ts(corn_embed_tst,start=1938), start=first_test_yr-60, end=first_test_yr)
  wheat_test <- window(ts(corn_embed_tst,start=1938), start=first_test_yr+1,end=first_test_yr+5)
  colnames(wheat_train) <- c("T","T-1","T-2","T-3","T-4")
  colnames(wheat_test) <- c("T","T-1","T-2","T-3","T-4")
  
  wheat_row <- c(first_test_yr, "wheat",rf_predictions(wheat_train, wheat_test), gbm_predictions(wheat_train, wheat_test), wheat_test[0:5])
  wheat_preds <- rbind(wheat_preds, wheat_row)

  soy_embed_tst <- embed(soy_ts,5)
  soy_train <- window(ts(soy_embed_tst,start=1938), start=first_test_yr-60, end=first_test_yr)
  soy_test <- window(ts(soy_embed_tst,start=1938), start=first_test_yr+1,end=first_test_yr+5)
  colnames(soy_train) <- c("T","T-1","T-2","T-3","T-4")
  colnames(soy_test) <- c("T","T-1","T-2","T-3","T-4")
  
  soy_row <- c(first_test_yr, "wheat",rf_predictions(soy_train, soy_test), gbm_predictions(soy_train, soy_test),soy_test[0:5])
  soy_preds <- rbind(soy_preds, soy_row)

}

prediction_df <- rbind(corn_preds,wheat_preds,soy_preds) %>% as.data.frame()

colnames(prediction_df) <- c("year", "crop", "rf t+1", "rf t+2", "rf t+3", "rf t+4", "rf t+5","true_value_t+1", "true_value_t+2", "true_value_t+3", "true_value_t+4", "true_value_t+5")

```

```{r}
write.csv(prediction_df, "../data/tree_predictions.csv", row.names = FALSE)
```

